; generated by PrusaSlicer 2.9.4 on 2026-04-21 at 18:11:47 UTC

; 

; external perimeters extrusion width = 0.70mm
; perimeters extrusion width = 0.70mm
; infill extrusion width = 0.70mm
; solid infill extrusion width = 0.70mm
; top infill extrusion width = 0.70mm
; first layer extrusion width = 0.70mm

M190 S60 ; set bed temperature and wait for it to be reached
M104 S215 ; set temperature
;TYPE:Custom
;Begin
M109 S215 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0 ; reset extrusion distance
; Filament gcode
M107 ; disable fan
;LAYER_CHANGE
;Z:0.45
;HEIGHT:0.45
G1 X2.991 Y3.186 F600 ; move to first layer point
G1 Z.45 ; move to first layer point
;TYPE:Skirt/Brim
;WIDTH:0.7
G1 F300
G1 X3.68 Y2.538 E.10678 ; skirt
G1 X5.904 Y1.526 E.38263 ; skirt
G1 X7.861 Y1.267 E.60549 ; skirt
G1 X47.861 Y1.267 E5.12127 ; skirt
G1 X50.271 Y1.664 E5.39701 ; skirt
G1 X52.426 Y2.814 E5.67277 ; skirt
G1 X54.098 Y4.595 E5.94856 ; skirt
G1 X55.11 Y6.818 E6.22431 ; skirt
G1 X55.369 Y8.776 E6.44728 ; skirt
G1 X55.369 Y48.776 E10.96306 ; skirt
G1 X54.972 Y51.186 E11.2388 ; skirt
G1 X53.822 Y53.341 E11.51456 ; skirt
G1 X52.041 Y55.013 E11.79035 ; skirt
G1 X49.818 Y56.025 E12.0661 ; skirt
G1 X47.861 Y56.284 E12.28896 ; skirt
G1 X7.861 Y56.284 E16.80474 ; skirt
G1 X5.45 Y55.887 E17.08059 ; skirt
G1 X3.295 Y54.737 E17.35635 ; skirt
G1 X1.623 Y52.956 E17.63214 ; skirt
G1 X.612 Y50.733 E17.90784 ; skirt
G1 X.352 Y48.776 E18.13072 ; skirt
G1 X.352 Y8.776 E22.6465 ; skirt
G1 X.749 Y6.365 E22.92235 ; skirt
G1 X1.899 Y4.21 E23.19811 ; skirt
G1 X2.991 Y3.186 E23.36711 ; skirt
G1 X3.391 Y3.644 F600 ; move to first skirt point
G1 F300
G1 X4.261 Y2.883 E23.4976 ; skirt
G1 X6.437 Y2.019 E23.76191 ; skirt
G1 X7.861 Y1.87 E23.92355 ; skirt
G1 X47.861 Y1.87 E28.43933 ; skirt
G1 X50.169 Y2.267 E28.70372 ; skirt
G1 X52.211 Y3.413 E28.96807 ; skirt
G1 X53.753 Y5.176 E29.23249 ; skirt
G1 X54.617 Y7.352 E29.4968 ; skirt
G1 X54.766 Y8.776 E29.65844 ; skirt
G1 X54.766 Y48.776 E34.17422 ; skirt
G1 X54.369 Y51.083 E34.4385 ; skirt
G1 X53.223 Y53.126 E34.70295 ; skirt
G1 X51.461 Y54.668 E34.96729 ; skirt
G1 X49.284 Y55.532 E35.23171 ; skirt
G1 X47.861 Y55.681 E35.39324 ; skirt
G1 X7.861 Y55.681 E39.90902 ; skirt
G1 X5.553 Y55.284 E40.17341 ; skirt
G1 X3.51 Y54.138 E40.43786 ; skirt
G1 X1.968 Y52.376 E40.7022 ; skirt
G1 X1.104 Y50.199 E40.96662 ; skirt
G1 X.956 Y48.776 E41.12814 ; skirt
G1 X.956 Y8.776 E45.64392 ; skirt
G1 X1.353 Y6.468 E45.90831 ; skirt
G1 X2.498 Y4.425 E46.17271 ; skirt
G1 X3.391 Y3.644 E46.30664 ; skirt
G1 X3.767 Y4.109 F600 ; move to first skirt point
G1 F300
G1 X4.837 Y3.247 E46.46176 ; skirt
G1 X7.861 Y2.474 E46.81413 ; skirt
G1 X47.861 Y2.474 E51.32991 ; skirt
G1 X50.062 Y2.871 E51.5824 ; skirt
G1 X51.985 Y4.011 E51.83478 ; skirt
G1 X53.389 Y5.752 E52.08728 ; skirt
G1 X54.162 Y8.776 E52.43965 ; skirt
G1 X54.162 Y48.776 E56.95543 ; skirt
G1 X53.766 Y50.976 E57.20779 ; skirt
G1 X52.625 Y52.9 E57.46032 ; skirt
G1 X50.884 Y54.304 E57.71282 ; skirt
G1 X47.861 Y55.077 E58.06508 ; skirt
G1 X7.861 Y55.077 E62.58086 ; skirt
G1 X5.66 Y54.68 E62.83335 ; skirt
G1 X3.736 Y53.54 E63.08582 ; skirt
G1 X2.332 Y51.799 E63.33832 ; skirt
G1 X1.559 Y48.776 E63.69058 ; skirt
G1 X1.559 Y8.776 E68.20636 ; skirt
G1 X1.956 Y6.575 E68.45885 ; skirt
G1 X3.096 Y4.651 E68.71132 ; skirt
G1 X3.767 Y4.109 E68.8087 ; skirt
G92 E0 ; reset extrusion distance
G92 E0 ; reset extrusion distance
G1 X47.511 Y48.426 F600 ; move to first perimeter point
;TYPE:External perimeter
;WIDTH:0.7
G1 F300
G1 X8.211 Y48.426 E4.43675 ; perimeter
G1 X8.211 Y9.126 E8.8735 ; perimeter
G1 X47.511 Y9.126 E13.31025 ; perimeter
G1 X47.511 Y48.426 E17.747 ; perimeter
;LAYER_CHANGE
;Z:0.9
;HEIGHT:0.45
G1 Z.9 F600 ; simple layer change
M104 S210 ; set temperature
G1 F300
G1 X8.211 Y48.426 E22.18375 ; perimeter
G1 X8.211 Y9.126 E26.6205 ; perimeter
G1 X47.511 Y9.126 E31.05725 ; perimeter
G1 X47.511 Y48.426 E35.494 ; perimeter
;LAYER_CHANGE
;Z:1.35
;HEIGHT:0.45
G1 Z1.35 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E39.93075 ; perimeter
G1 X8.211 Y9.126 E44.3675 ; perimeter
G1 X47.511 Y9.126 E48.80425 ; perimeter
G1 X47.511 Y48.426 E53.241 ; perimeter
;LAYER_CHANGE
;Z:1.8
;HEIGHT:0.45
G1 Z1.8 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E57.67775 ; perimeter
G1 X8.211 Y9.126 E62.1145 ; perimeter
G1 X47.511 Y9.126 E66.55125 ; perimeter
G1 X47.511 Y48.426 E70.988 ; perimeter
;LAYER_CHANGE
;Z:2.25
;HEIGHT:0.45
G1 Z2.25 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E75.42475 ; perimeter
G1 X8.211 Y9.126 E79.8615 ; perimeter
G1 X47.511 Y9.126 E84.29825 ; perimeter
G1 X47.511 Y48.426 E88.735 ; perimeter
;LAYER_CHANGE
;Z:2.7
;HEIGHT:0.45
G1 Z2.7 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E93.17175 ; perimeter
G1 X8.211 Y9.126 E97.6085 ; perimeter
G1 X47.511 Y9.126 E102.04525 ; perimeter
G1 X47.511 Y48.426 E106.482 ; perimeter
;LAYER_CHANGE
;Z:3.15
;HEIGHT:0.45
G1 Z3.15 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E110.91875 ; perimeter
G1 X8.211 Y9.126 E115.3555 ; perimeter
G1 X47.511 Y9.126 E119.79225 ; perimeter
G1 X47.511 Y48.426 E124.229 ; perimeter
;LAYER_CHANGE
;Z:3.6
;HEIGHT:0.45
G1 Z3.6 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E128.66575 ; perimeter
G1 X8.211 Y9.126 E133.1025 ; perimeter
G1 X47.511 Y9.126 E137.53925 ; perimeter
G1 X47.511 Y48.426 E141.976 ; perimeter
;LAYER_CHANGE
;Z:4.05
;HEIGHT:0.45
G1 Z4.05 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E146.41275 ; perimeter
G1 X8.211 Y9.126 E150.8495 ; perimeter
G1 X47.511 Y9.126 E155.28625 ; perimeter
G1 X47.511 Y48.426 E159.723 ; perimeter
;LAYER_CHANGE
;Z:4.5
;HEIGHT:0.45
G1 Z4.5 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E164.15975 ; perimeter
G1 X8.211 Y9.126 E168.5965 ; perimeter
G1 X47.511 Y9.126 E173.03325 ; perimeter
G1 X47.511 Y48.426 E177.47 ; perimeter
;LAYER_CHANGE
;Z:4.95
;HEIGHT:0.45
G1 Z4.95 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E181.90675 ; perimeter
G1 X8.211 Y9.126 E186.3435 ; perimeter
G1 X47.511 Y9.126 E190.78025 ; perimeter
G1 X47.511 Y48.426 E195.217 ; perimeter
;LAYER_CHANGE
;Z:5.4
;HEIGHT:0.45
G1 Z5.4 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E199.65375 ; perimeter
G1 X8.211 Y9.126 E204.0905 ; perimeter
G1 X47.511 Y9.126 E208.52725 ; perimeter
G1 X47.511 Y48.426 E212.964 ; perimeter
;LAYER_CHANGE
;Z:5.85
;HEIGHT:0.45
G1 Z5.85 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E217.40075 ; perimeter
G1 X8.211 Y9.126 E221.8375 ; perimeter
G1 X47.511 Y9.126 E226.27425 ; perimeter
G1 X47.511 Y48.426 E230.711 ; perimeter
;LAYER_CHANGE
;Z:6.3
;HEIGHT:0.45
G1 Z6.3 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E235.14775 ; perimeter
G1 X8.211 Y9.126 E239.5845 ; perimeter
G1 X47.511 Y9.126 E244.02125 ; perimeter
G1 X47.511 Y48.426 E248.458 ; perimeter
;LAYER_CHANGE
;Z:6.75
;HEIGHT:0.45
G1 Z6.75 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E252.89475 ; perimeter
G1 X8.211 Y9.126 E257.3315 ; perimeter
G1 X47.511 Y9.126 E261.76825 ; perimeter
G1 X47.511 Y48.426 E266.205 ; perimeter
;LAYER_CHANGE
;Z:7.2
;HEIGHT:0.45
G1 Z7.2 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E270.64175 ; perimeter
G1 X8.211 Y9.126 E275.0785 ; perimeter
G1 X47.511 Y9.126 E279.51525 ; perimeter
G1 X47.511 Y48.426 E283.952 ; perimeter
;LAYER_CHANGE
;Z:7.65
;HEIGHT:0.45
G1 Z7.65 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E288.38875 ; perimeter
G1 X8.211 Y9.126 E292.8255 ; perimeter
G1 X47.511 Y9.126 E297.26225 ; perimeter
G1 X47.511 Y48.426 E301.699 ; perimeter
;LAYER_CHANGE
;Z:8.1
;HEIGHT:0.45
G1 Z8.1 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E306.13575 ; perimeter
G1 X8.211 Y9.126 E310.5725 ; perimeter
G1 X47.511 Y9.126 E315.00925 ; perimeter
G1 X47.511 Y48.426 E319.446 ; perimeter
;LAYER_CHANGE
;Z:8.55
;HEIGHT:0.45
G1 Z8.55 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E323.88275 ; perimeter
G1 X8.211 Y9.126 E328.3195 ; perimeter
G1 X47.511 Y9.126 E332.75625 ; perimeter
G1 X47.511 Y48.426 E337.193 ; perimeter
;LAYER_CHANGE
;Z:9
;HEIGHT:0.45
G1 Z9 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E341.62975 ; perimeter
G1 X8.211 Y9.126 E346.0665 ; perimeter
G1 X47.511 Y9.126 E350.50325 ; perimeter
G1 X47.511 Y48.426 E354.94 ; perimeter
;LAYER_CHANGE
;Z:9.45
;HEIGHT:0.45
G1 Z9.45 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E359.37675 ; perimeter
G1 X8.211 Y9.126 E363.8135 ; perimeter
G1 X47.511 Y9.126 E368.25025 ; perimeter
G1 X47.511 Y48.426 E372.687 ; perimeter
;LAYER_CHANGE
;Z:9.9
;HEIGHT:0.45
G1 Z9.9 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E377.12375 ; perimeter
G1 X8.211 Y9.126 E381.5605 ; perimeter
G1 X47.511 Y9.126 E385.99725 ; perimeter
G1 X47.511 Y48.426 E390.434 ; perimeter
;LAYER_CHANGE
;Z:10.35
;HEIGHT:0.450001
G1 Z10.35 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E394.87075 ; perimeter
G1 X8.211 Y9.126 E399.3075 ; perimeter
G1 X47.511 Y9.126 E403.74425 ; perimeter
G1 X47.511 Y48.426 E408.181 ; perimeter
;LAYER_CHANGE
;Z:10.8
;HEIGHT:0.45
G1 Z10.8 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E412.61775 ; perimeter
G1 X8.211 Y9.126 E417.0545 ; perimeter
G1 X47.511 Y9.126 E421.49125 ; perimeter
G1 X47.511 Y48.426 E425.928 ; perimeter
;LAYER_CHANGE
;Z:11.25
;HEIGHT:0.45
G1 Z11.25 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E430.36475 ; perimeter
G1 X8.211 Y9.126 E434.8015 ; perimeter
G1 X47.511 Y9.126 E439.23825 ; perimeter
G1 X47.511 Y48.426 E443.675 ; perimeter
;LAYER_CHANGE
;Z:11.7
;HEIGHT:0.45
G1 Z11.7 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E448.11175 ; perimeter
G1 X8.211 Y9.126 E452.5485 ; perimeter
G1 X47.511 Y9.126 E456.98525 ; perimeter
G1 X47.511 Y48.426 E461.422 ; perimeter
;LAYER_CHANGE
;Z:12.15
;HEIGHT:0.45
G1 Z12.15 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E465.85875 ; perimeter
G1 X8.211 Y9.126 E470.2955 ; perimeter
G1 X47.511 Y9.126 E474.73225 ; perimeter
G1 X47.511 Y48.426 E479.169 ; perimeter
;LAYER_CHANGE
;Z:12.6
;HEIGHT:0.450001
G1 Z12.6 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E483.60575 ; perimeter
G1 X8.211 Y9.126 E488.0425 ; perimeter
G1 X47.511 Y9.126 E492.47925 ; perimeter
G1 X47.511 Y48.426 E496.916 ; perimeter
;LAYER_CHANGE
;Z:13.05
;HEIGHT:0.45
G1 Z13.05 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E501.35275 ; perimeter
G1 X8.211 Y9.126 E505.7895 ; perimeter
G1 X47.511 Y9.126 E510.22625 ; perimeter
G1 X47.511 Y48.426 E514.663 ; perimeter
;LAYER_CHANGE
;Z:13.5
;HEIGHT:0.45
G1 Z13.5 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E519.09975 ; perimeter
G1 X8.211 Y9.126 E523.5365 ; perimeter
G1 X47.511 Y9.126 E527.97325 ; perimeter
G1 X47.511 Y48.426 E532.41 ; perimeter
;LAYER_CHANGE
;Z:13.95
;HEIGHT:0.45
G1 Z13.95 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E536.84675 ; perimeter
G1 X8.211 Y9.126 E541.2835 ; perimeter
G1 X47.511 Y9.126 E545.72025 ; perimeter
G1 X47.511 Y48.426 E550.157 ; perimeter
;LAYER_CHANGE
;Z:14.4
;HEIGHT:0.45
G1 Z14.4 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E554.59375 ; perimeter
G1 X8.211 Y9.126 E559.0305 ; perimeter
G1 X47.511 Y9.126 E563.46725 ; perimeter
G1 X47.511 Y48.426 E567.904 ; perimeter
;LAYER_CHANGE
;Z:14.85
;HEIGHT:0.450001
G1 Z14.85 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E572.34075 ; perimeter
G1 X8.211 Y9.126 E576.7775 ; perimeter
G1 X47.511 Y9.126 E581.21425 ; perimeter
G1 X47.511 Y48.426 E585.651 ; perimeter
;LAYER_CHANGE
;Z:15.3
;HEIGHT:0.45
G1 Z15.3 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E590.08775 ; perimeter
G1 X8.211 Y9.126 E594.5245 ; perimeter
G1 X47.511 Y9.126 E598.96125 ; perimeter
G1 X47.511 Y48.426 E603.398 ; perimeter
;LAYER_CHANGE
;Z:15.75
;HEIGHT:0.45
G1 Z15.75 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E607.83475 ; perimeter
G1 X8.211 Y9.126 E612.2715 ; perimeter
G1 X47.511 Y9.126 E616.70825 ; perimeter
G1 X47.511 Y48.426 E621.145 ; perimeter
;LAYER_CHANGE
;Z:16.2
;HEIGHT:0.450001
G1 Z16.2 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E625.58175 ; perimeter
G1 X8.211 Y9.126 E630.0185 ; perimeter
G1 X47.511 Y9.126 E634.45525 ; perimeter
G1 X47.511 Y48.426 E638.892 ; perimeter
;LAYER_CHANGE
;Z:16.65
;HEIGHT:0.449999
G1 Z16.65 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E643.32875 ; perimeter
G1 X8.211 Y9.126 E647.7655 ; perimeter
G1 X47.511 Y9.126 E652.20225 ; perimeter
G1 X47.511 Y48.426 E656.639 ; perimeter
;LAYER_CHANGE
;Z:17.1
;HEIGHT:0.450001
G1 Z17.1 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E661.07575 ; perimeter
G1 X8.211 Y9.126 E665.5125 ; perimeter
G1 X47.511 Y9.126 E669.94925 ; perimeter
G1 X47.511 Y48.426 E674.386 ; perimeter
;LAYER_CHANGE
;Z:17.55
;HEIGHT:0.449999
G1 Z17.55 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E678.82275 ; perimeter
G1 X8.211 Y9.126 E683.2595 ; perimeter
G1 X47.511 Y9.126 E687.69625 ; perimeter
G1 X47.511 Y48.426 E692.133 ; perimeter
;LAYER_CHANGE
;Z:18
;HEIGHT:0.450001
G1 Z18 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E696.56975 ; perimeter
G1 X8.211 Y9.126 E701.0065 ; perimeter
G1 X47.511 Y9.126 E705.44325 ; perimeter
G1 X47.511 Y48.426 E709.88 ; perimeter
;LAYER_CHANGE
;Z:18.45
;HEIGHT:0.450001
G1 Z18.45 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E714.31675 ; perimeter
G1 X8.211 Y9.126 E718.7535 ; perimeter
G1 X47.511 Y9.126 E723.19025 ; perimeter
G1 X47.511 Y48.426 E727.627 ; perimeter
;LAYER_CHANGE
;Z:18.9
;HEIGHT:0.449999
G1 Z18.9 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E732.06375 ; perimeter
G1 X8.211 Y9.126 E736.5005 ; perimeter
G1 X47.511 Y9.126 E740.93725 ; perimeter
G1 X47.511 Y48.426 E745.374 ; perimeter
;LAYER_CHANGE
;Z:19.35
;HEIGHT:0.450001
G1 Z19.35 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E749.81075 ; perimeter
G1 X8.211 Y9.126 E754.2475 ; perimeter
G1 X47.511 Y9.126 E758.68425 ; perimeter
G1 X47.511 Y48.426 E763.121 ; perimeter
;LAYER_CHANGE
;Z:19.8
;HEIGHT:0.449999
G1 Z19.8 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E767.55775 ; perimeter
G1 X8.211 Y9.126 E771.9945 ; perimeter
G1 X47.511 Y9.126 E776.43125 ; perimeter
G1 X47.511 Y48.426 E780.868 ; perimeter
;LAYER_CHANGE
;Z:20.25
;HEIGHT:0.450001
G1 Z20.25 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E785.30475 ; perimeter
G1 X8.211 Y9.126 E789.7415 ; perimeter
G1 X47.511 Y9.126 E794.17825 ; perimeter
G1 X47.511 Y48.426 E798.615 ; perimeter
;LAYER_CHANGE
;Z:20.7
;HEIGHT:0.450001
G1 Z20.7 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E803.05175 ; perimeter
G1 X8.211 Y9.126 E807.4885 ; perimeter
G1 X47.511 Y9.126 E811.92525 ; perimeter
G1 X47.511 Y48.426 E816.362 ; perimeter
;LAYER_CHANGE
;Z:21.15
;HEIGHT:0.449999
G1 Z21.15 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E820.79875 ; perimeter
G1 X8.211 Y9.126 E825.2355 ; perimeter
G1 X47.511 Y9.126 E829.67225 ; perimeter
G1 X47.511 Y48.426 E834.109 ; perimeter
;LAYER_CHANGE
;Z:21.6
;HEIGHT:0.450001
G1 Z21.6 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E838.54575 ; perimeter
G1 X8.211 Y9.126 E842.9825 ; perimeter
G1 X47.511 Y9.126 E847.41925 ; perimeter
G1 X47.511 Y48.426 E851.856 ; perimeter
;LAYER_CHANGE
;Z:22.05
;HEIGHT:0.449999
G1 Z22.05 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E856.29275 ; perimeter
G1 X8.211 Y9.126 E860.7295 ; perimeter
G1 X47.511 Y9.126 E865.16625 ; perimeter
G1 X47.511 Y48.426 E869.603 ; perimeter
;LAYER_CHANGE
;Z:22.5
;HEIGHT:0.450001
G1 Z22.5 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E874.03975 ; perimeter
G1 X8.211 Y9.126 E878.4765 ; perimeter
G1 X47.511 Y9.126 E882.91325 ; perimeter
G1 X47.511 Y48.426 E887.35 ; perimeter
;LAYER_CHANGE
;Z:22.95
;HEIGHT:0.450001
G1 Z22.95 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E891.78675 ; perimeter
G1 X8.211 Y9.126 E896.2235 ; perimeter
G1 X47.511 Y9.126 E900.66025 ; perimeter
G1 X47.511 Y48.426 E905.097 ; perimeter
;LAYER_CHANGE
;Z:23.4
;HEIGHT:0.449999
G1 Z23.4 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E909.53375 ; perimeter
G1 X8.211 Y9.126 E913.9705 ; perimeter
G1 X47.511 Y9.126 E918.40725 ; perimeter
G1 X47.511 Y48.426 E922.844 ; perimeter
;LAYER_CHANGE
;Z:23.85
;HEIGHT:0.450001
G1 Z23.85 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E927.28075 ; perimeter
G1 X8.211 Y9.126 E931.7175 ; perimeter
G1 X47.511 Y9.126 E936.15425 ; perimeter
G1 X47.511 Y48.426 E940.591 ; perimeter
;LAYER_CHANGE
;Z:24.3
;HEIGHT:0.449999
G1 Z24.3 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E945.02775 ; perimeter
G1 X8.211 Y9.126 E949.4645 ; perimeter
G1 X47.511 Y9.126 E953.90125 ; perimeter
G1 X47.511 Y48.426 E958.338 ; perimeter
;LAYER_CHANGE
;Z:24.75
;HEIGHT:0.450001
G1 Z24.75 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E962.77475 ; perimeter
G1 X8.211 Y9.126 E967.2115 ; perimeter
G1 X47.511 Y9.126 E971.64825 ; perimeter
G1 X47.511 Y48.426 E976.085 ; perimeter
;LAYER_CHANGE
;Z:25.2
;HEIGHT:0.450001
G1 Z25.2 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E980.52175 ; perimeter
G1 X8.211 Y9.126 E984.9585 ; perimeter
G1 X47.511 Y9.126 E989.39525 ; perimeter
G1 X47.511 Y48.426 E993.832 ; perimeter
;LAYER_CHANGE
;Z:25.65
;HEIGHT:0.449999
G1 Z25.65 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E998.26875 ; perimeter
G1 X8.211 Y9.126 E1002.7055 ; perimeter
G1 X47.511 Y9.126 E1007.14225 ; perimeter
G1 X47.511 Y48.426 E1011.579 ; perimeter
;LAYER_CHANGE
;Z:26.1
;HEIGHT:0.450001
G1 Z26.1 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1016.01575 ; perimeter
G1 X8.211 Y9.126 E1020.4525 ; perimeter
G1 X47.511 Y9.126 E1024.88925 ; perimeter
G1 X47.511 Y48.426 E1029.326 ; perimeter
;LAYER_CHANGE
;Z:26.55
;HEIGHT:0.449999
G1 Z26.55 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1033.76275 ; perimeter
G1 X8.211 Y9.126 E1038.1995 ; perimeter
G1 X47.511 Y9.126 E1042.63625 ; perimeter
G1 X47.511 Y48.426 E1047.073 ; perimeter
;LAYER_CHANGE
;Z:27
;HEIGHT:0.450001
G1 Z27 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1051.50975 ; perimeter
G1 X8.211 Y9.126 E1055.9465 ; perimeter
G1 X47.511 Y9.126 E1060.38325 ; perimeter
G1 X47.511 Y48.426 E1064.82 ; perimeter
;LAYER_CHANGE
;Z:27.45
;HEIGHT:0.450001
G1 Z27.45 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1069.25675 ; perimeter
G1 X8.211 Y9.126 E1073.6935 ; perimeter
G1 X47.511 Y9.126 E1078.13025 ; perimeter
G1 X47.511 Y48.426 E1082.567 ; perimeter
;LAYER_CHANGE
;Z:27.9
;HEIGHT:0.449999
G1 Z27.9 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1087.00375 ; perimeter
G1 X8.211 Y9.126 E1091.4405 ; perimeter
G1 X47.511 Y9.126 E1095.87725 ; perimeter
G1 X47.511 Y48.426 E1100.314 ; perimeter
;LAYER_CHANGE
;Z:28.35
;HEIGHT:0.450001
G1 Z28.35 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1104.75075 ; perimeter
G1 X8.211 Y9.126 E1109.1875 ; perimeter
G1 X47.511 Y9.126 E1113.62425 ; perimeter
G1 X47.511 Y48.426 E1118.061 ; perimeter
;LAYER_CHANGE
;Z:28.8
;HEIGHT:0.449999
G1 Z28.8 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1122.49775 ; perimeter
G1 X8.211 Y9.126 E1126.9345 ; perimeter
G1 X47.511 Y9.126 E1131.37125 ; perimeter
G1 X47.511 Y48.426 E1135.808 ; perimeter
;LAYER_CHANGE
;Z:29.25
;HEIGHT:0.450001
G1 Z29.25 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1140.24475 ; perimeter
G1 X8.211 Y9.126 E1144.6815 ; perimeter
G1 X47.511 Y9.126 E1149.11825 ; perimeter
G1 X47.511 Y48.426 E1153.555 ; perimeter
;LAYER_CHANGE
;Z:29.7
;HEIGHT:0.450001
G1 Z29.7 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1157.99175 ; perimeter
G1 X8.211 Y9.126 E1162.4285 ; perimeter
G1 X47.511 Y9.126 E1166.86525 ; perimeter
G1 X47.511 Y48.426 E1171.302 ; perimeter
;LAYER_CHANGE
;Z:30.15
;HEIGHT:0.449999
G1 Z30.15 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1175.73875 ; perimeter
G1 X8.211 Y9.126 E1180.1755 ; perimeter
G1 X47.511 Y9.126 E1184.61225 ; perimeter
G1 X47.511 Y48.426 E1189.049 ; perimeter
;LAYER_CHANGE
;Z:30.6
;HEIGHT:0.450001
G1 Z30.6 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1193.48575 ; perimeter
G1 X8.211 Y9.126 E1197.9225 ; perimeter
G1 X47.511 Y9.126 E1202.35925 ; perimeter
G1 X47.511 Y48.426 E1206.796 ; perimeter
;LAYER_CHANGE
;Z:31.05
;HEIGHT:0.449999
G1 Z31.05 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1211.23275 ; perimeter
G1 X8.211 Y9.126 E1215.6695 ; perimeter
G1 X47.511 Y9.126 E1220.10625 ; perimeter
G1 X47.511 Y48.426 E1224.543 ; perimeter
;LAYER_CHANGE
;Z:31.5
;HEIGHT:0.450001
G1 Z31.5 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1228.97975 ; perimeter
G1 X8.211 Y9.126 E1233.4165 ; perimeter
G1 X47.511 Y9.126 E1237.85325 ; perimeter
G1 X47.511 Y48.426 E1242.29 ; perimeter
;LAYER_CHANGE
;Z:31.95
;HEIGHT:0.450001
G1 Z31.95 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1246.72675 ; perimeter
G1 X8.211 Y9.126 E1251.1635 ; perimeter
G1 X47.511 Y9.126 E1255.60025 ; perimeter
G1 X47.511 Y48.426 E1260.037 ; perimeter
;LAYER_CHANGE
;Z:32.4
;HEIGHT:0.450001
G1 Z32.4 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1264.47375 ; perimeter
G1 X8.211 Y9.126 E1268.9105 ; perimeter
G1 X47.511 Y9.126 E1273.34725 ; perimeter
G1 X47.511 Y48.426 E1277.784 ; perimeter
;LAYER_CHANGE
;Z:32.85
;HEIGHT:0.449997
G1 Z32.85 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1282.22075 ; perimeter
G1 X8.211 Y9.126 E1286.6575 ; perimeter
G1 X47.511 Y9.126 E1291.09425 ; perimeter
G1 X47.511 Y48.426 E1295.531 ; perimeter
;LAYER_CHANGE
;Z:33.3
;HEIGHT:0.450001
G1 Z33.3 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1299.96775 ; perimeter
G1 X8.211 Y9.126 E1304.4045 ; perimeter
G1 X47.511 Y9.126 E1308.84125 ; perimeter
G1 X47.511 Y48.426 E1313.278 ; perimeter
;LAYER_CHANGE
;Z:33.75
;HEIGHT:0.450001
G1 Z33.75 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1317.71475 ; perimeter
G1 X8.211 Y9.126 E1322.1515 ; perimeter
G1 X47.511 Y9.126 E1326.58825 ; perimeter
G1 X47.511 Y48.426 E1331.025 ; perimeter
;LAYER_CHANGE
;Z:34.2
;HEIGHT:0.450001
G1 Z34.2 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1335.46175 ; perimeter
G1 X8.211 Y9.126 E1339.8985 ; perimeter
G1 X47.511 Y9.126 E1344.33525 ; perimeter
G1 X47.511 Y48.426 E1348.772 ; perimeter
;LAYER_CHANGE
;Z:34.65
;HEIGHT:0.450001
G1 Z34.65 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1353.20875 ; perimeter
G1 X8.211 Y9.126 E1357.6455 ; perimeter
G1 X47.511 Y9.126 E1362.08225 ; perimeter
G1 X47.511 Y48.426 E1366.519 ; perimeter
;LAYER_CHANGE
;Z:35.1
;HEIGHT:0.449997
G1 Z35.1 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1370.95575 ; perimeter
G1 X8.211 Y9.126 E1375.3925 ; perimeter
G1 X47.511 Y9.126 E1379.82925 ; perimeter
G1 X47.511 Y48.426 E1384.266 ; perimeter
;LAYER_CHANGE
;Z:35.55
;HEIGHT:0.450001
G1 Z35.55 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1388.70275 ; perimeter
G1 X8.211 Y9.126 E1393.1395 ; perimeter
G1 X47.511 Y9.126 E1397.57625 ; perimeter
G1 X47.511 Y48.426 E1402.013 ; perimeter
;LAYER_CHANGE
;Z:36
;HEIGHT:0.450001
G1 Z36 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1406.44975 ; perimeter
G1 X8.211 Y9.126 E1410.8865 ; perimeter
G1 X47.511 Y9.126 E1415.32325 ; perimeter
G1 X47.511 Y48.426 E1419.76 ; perimeter
;LAYER_CHANGE
;Z:36.45
;HEIGHT:0.450001
G1 Z36.45 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1424.19675 ; perimeter
G1 X8.211 Y9.126 E1428.6335 ; perimeter
G1 X47.511 Y9.126 E1433.07025 ; perimeter
G1 X47.511 Y48.426 E1437.507 ; perimeter
;LAYER_CHANGE
;Z:36.9
;HEIGHT:0.450001
G1 Z36.9 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1441.94375 ; perimeter
G1 X8.211 Y9.126 E1446.3805 ; perimeter
G1 X47.511 Y9.126 E1450.81725 ; perimeter
G1 X47.511 Y48.426 E1455.254 ; perimeter
;LAYER_CHANGE
;Z:37.35
;HEIGHT:0.449997
G1 Z37.35 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1459.69075 ; perimeter
G1 X8.211 Y9.126 E1464.1275 ; perimeter
G1 X47.511 Y9.126 E1468.56425 ; perimeter
G1 X47.511 Y48.426 E1473.001 ; perimeter
;LAYER_CHANGE
;Z:37.8
;HEIGHT:0.450001
G1 Z37.8 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1477.43775 ; perimeter
G1 X8.211 Y9.126 E1481.8745 ; perimeter
G1 X47.511 Y9.126 E1486.31125 ; perimeter
G1 X47.511 Y48.426 E1490.748 ; perimeter
;LAYER_CHANGE
;Z:38.25
;HEIGHT:0.450001
G1 Z38.25 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1495.18475 ; perimeter
G1 X8.211 Y9.126 E1499.6215 ; perimeter
G1 X47.511 Y9.126 E1504.05825 ; perimeter
G1 X47.511 Y48.426 E1508.495 ; perimeter
;LAYER_CHANGE
;Z:38.7
;HEIGHT:0.450001
G1 Z38.7 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1512.93175 ; perimeter
G1 X8.211 Y9.126 E1517.3685 ; perimeter
G1 X47.511 Y9.126 E1521.80525 ; perimeter
G1 X47.511 Y48.426 E1526.242 ; perimeter
;LAYER_CHANGE
;Z:39.15
;HEIGHT:0.450001
G1 Z39.15 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1530.67875 ; perimeter
G1 X8.211 Y9.126 E1535.1155 ; perimeter
G1 X47.511 Y9.126 E1539.55225 ; perimeter
G1 X47.511 Y48.426 E1543.989 ; perimeter
;LAYER_CHANGE
;Z:39.6
;HEIGHT:0.449997
G1 Z39.6 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1548.42575 ; perimeter
G1 X8.211 Y9.126 E1552.8625 ; perimeter
G1 X47.511 Y9.126 E1557.29925 ; perimeter
G1 X47.511 Y48.426 E1561.736 ; perimeter
;LAYER_CHANGE
;Z:40.05
;HEIGHT:0.450001
G1 Z40.05 F600 ; simple layer change
G1 F300
G1 X8.211 Y48.426 E1566.17275 ; perimeter
G1 X8.211 Y9.126 E1570.6095 ; perimeter
G1 X47.511 Y9.126 E1575.04625 ; perimeter
G1 X47.511 Y48.426 E1579.483 ; perimeter
G92 E0 ; reset extrusion distance
M107 ; disable fan
;TYPE:Custom
; Filament-specific end gcode
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; objects_info = {"objects":[]}
; filament used [mm] = 1648.29
; filament used [cm3] = 3.96
; filament used [g] = 4.92
; filament cost = 0.12
; total filament used [g] = 4.92
; total filament cost = 0.12
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 49m 1s
; estimated printing time (silent mode) = 49m 3s
; estimated first layer printing time (normal mode) = 2m 40s
; estimated first layer printing time (silent mode) = 2m 40s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 60
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 0
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 18
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; compatible_printers_condition_cummulative = ;"printer_notes!~/.*NO_TEMPLATES.*/ and printer_notes!~/.*PRINTER_VENDOR_TRILAB.*/ and printer_notes!~/.*PRINTER_MODEL_MK4IS.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and num_extruders>1)"
; complete_objects = 0
; cooling = 0
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; default_filament_profile = 
; default_print_profile = 
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = partial
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.7
; external_perimeter_speed = 5
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.7
; fan_always_on = 0
; fan_below_layer_time = 100
; filament_abrasive = 0
; filament_colour = #FF8000
; filament_cooling_final_speed = 2
; filament_cooling_initial_speed = 3
; filament_cooling_moves = 1
; filament_cost = 25.4
; filament_density = 1.24
; filament_deretract_speed = nil
; filament_diameter = 1.75
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 14
; filament_loading_speed_start = 19
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 0
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "130 120 2.70968 2.93548 3.32258 3.83871 4.58065 5.54839 6.51613 7.35484 7.93548 8.16129| 0.05 2.66451 0.45 3.05805 0.95 4.05807 1.45 5.97742 1.95 7.69999 2.45 8.1936 2.95 11.342 3.45 11.4065 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_retract_before_travel = nil
; filament_retract_before_wipe = nil
; filament_retract_layer_change = nil
; filament_retract_length = nil
; filament_retract_length_toolchange = nil
; filament_retract_lift = nil
; filament_retract_lift_above = nil
; filament_retract_lift_below = nil
; filament_retract_restart_extra = nil
; filament_retract_restart_extra_toolchange = nil
; filament_retract_speed = nil
; filament_seam_gap_distance = nil
; filament_settings_id = "UR5e Prusaslicer Config.ini (UR5e PLA)"
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_travel_lift_before_obstacle = nil
; filament_travel_max_lift = nil
; filament_travel_ramping_lift = nil
; filament_travel_slope = nil
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 20
; filament_unloading_speed_start = 100
; filament_vendor = Generic
; filament_wipe = nil
; fill_angle = 45
; fill_density = 0%
; fill_pattern = rectilinear
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.7
; first_layer_height = 0.45
; first_layer_infill_speed = 0
; first_layer_speed = 5
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 3
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 0
; gap_fill_speed = 5
; gcode_comments = 1
; gcode_flavor = marlin2
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.7
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 22
; inherits_cummulative = ;"Generic PLA @Template";
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.45
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.6
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 0
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.7
; perimeter_generator = arachne
; perimeter_speed = 5
; perimeters = 1
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = UR5e DEV Delay Calibration
; printer_model = 
; printer_notes = 
; printer_settings_id = UR5e Prusaslicer Config.ini (UR5e)
; printer_technology = FFF
; printer_variant = 
; printer_vendor = 
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 0
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 0
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 0
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 3
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 5
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.7
; solid_infill_speed = 21
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = ;Begin\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 0
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 5
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.7
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 20
; top_solid_layers = 0
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 10
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 0
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
